"""phase3 add scope user_id to documents chunks and report status

Revision ID: 4dc56b5b074c
Revises: afc2a56ca28e
Create Date: 2026-06-23 00:24:28.863893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc56b5b074c'
down_revision: Union[str, Sequence[str], None] = 'afc2a56ca28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('scope', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_chunks_scope'), 'chunks', ['scope'], unique=False)
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('scope', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_documents_scope'), 'documents', ['scope'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_scope'), table_name='documents')
    op.drop_column('documents', 'scope')
    op.drop_column('documents', 'user_id')
    op.drop_index(op.f('ix_chunks_scope'), table_name='chunks')
    op.drop_column('chunks', 'scope')
    # ### end Alembic commands ###
